
exports = PAYMENT_GATEWAY = {
    stripe: 'Stripe',
};

exports = LANGUAGES = {
    english : 'English',
    arebic : 'Arebic'
};

exports = TRIP_STATUS = {
    WAITING_FOR_PROVIDER: 9,
    NO_PROVIDER_FOUND: 109,
    NOT_ANSWERED: 110,
    PROVIDER_ACCEPTED: 11,
    PROVIDER_REJECTED: 111,
    PROVIDER_CANCELLED: 112,
    TRIP_COMPLETED: 25,
    INITIATE_TRIP: 50
};


// ORDER_CANCELLATION_CHARGE CONSTANT
exports = VEHICLE_ACCESIBILITY_TYPE = {
    BABY_SEAT: "baby_seat",
    HOTSPOTS: "hotspot",
    HANDICAPE: "handicap"
};
exports = VEHICLE_ACCESIBILITY_TYPE_STRING = {
    BABY_SEAT: "Baby Seat",
    HOTSPOTS: "Hotspot",
    HANDICAPE: "Handicap"
};




// VEHICLE_ACCESIBILITY CONSTANT ARRAY 
exports = VEHICLE_ACCESIBILITY = [
    {ID: VEHICLE_ACCESIBILITY_TYPE.BABY_SEAT, NAME: VEHICLE_ACCESIBILITY_TYPE_STRING.BABY_SEAT},
    {ID: VEHICLE_ACCESIBILITY_TYPE.HOTSPOTS, NAME: VEHICLE_ACCESIBILITY_TYPE_STRING.HOTSPOTS},
    {ID: VEHICLE_ACCESIBILITY_TYPE.HANDICAPE, NAME: VEHICLE_ACCESIBILITY_TYPE_STRING.HANDICAPE}


];

